"""
compute_deltas.py

Computes verb and noun Delta metrics for all stimuli items.

Delta_word = cosine_similarity(X[word], Y[word])
  X[word] = mean embedding across ALL available contexts for that word
            (the word's "prototype" — what it looks like on average in the corpus)
  Y[word] = mean embedding for that word in the specific stimuli pair (mean of 100 KWICs)
            (what the word looks like in this particular verb-noun combination)

A high Delta (close to 1.0) means the item-specific embedding is close to the prototype
  → the word is being used conventionally → expected for productive items

A low Delta means the embedding has shifted away from the prototype
  → the word is being used in a specialised/idiomatic way → expected for collocations

Sources:
  output/verbs.pt  -> X[verb], Y[verb], Y[noun]  (verb is seed, ~2.6 GB)
  output/nouns.pt  -> X[noun]                    (noun is seed, ~5.2 GB)

  verbs.pt: 95 seed verbs × their top n Sketch Engine noun collocates. Both the verb
  and noun embedding are stored for every pair, so a noun that co-occurs with multiple
  seed verbs will accumulate embeddings from each of those verb contexts.

  nouns.pt: 185 seed nouns × their top n Sketch Engine verb collocates. Again both
  embeddings are stored, so a verb that co-occurs with multiple seed nouns accumulates
  embeddings from each of those noun contexts.

  We prefer X[verb] from verbs.pt because the verb was the seed there — Sketch Engine
  systematically retrieved its top collocates, so coverage of the verb's contexts is
  most complete. Same logic for preferring X[noun] from nouns.pt.
  Y[verb] and Y[noun] both come from verbs.pt because stimuli were queried by verb.

Writes:
  output/verb_noun_deltas.csv   one row per stimuli item
"""

from pathlib import Path
import argparse
import warnings
import torch
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


ROOT      = Path(__file__).parent
VERBS_PT  = ROOT / 'output' / 'output_verbs' / 'verbs.pt'
NOUNS_PT  = ROOT / 'output' / 'output_nouns' / 'nouns.pt'

parser = argparse.ArgumentParser(description="Compute LSCD delta metrics for a stimuli CSV.")
parser.add_argument('--stimuli', default=str(ROOT / 'data' / 'iRT_AJT.csv'),
                    help='Path to stimuli CSV (must have verb, noun, Condition, Item columns)')
parser.add_argument('--output',  default=str(ROOT / 'output' / 'verb_noun_deltas.csv'),
                    help='Path to write output CSV')
args = parser.parse_args()

STIMULI = Path(args.stimuli)
OUT     = Path(args.output)


for path, name in [(VERBS_PT, 'verbs.pt'), (NOUNS_PT, 'nouns.pt'), (STIMULI, 'iRT_AJT.csv')]:
    if not path.exists():
        raise FileNotFoundError(
            f"{name} not found at {path}\n"
            f"  verbs.pt and nouns.pt must be transferred to the cluster PVC before running."
        )

# .pt files are too large for VRAM so always load to CPU.
# Final pooled vectors (one per word) are moved to DEVICE for cosine similarity.
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

# ---------------------------------------------------------------------------

def pair_mean_emb(rec, key):
    """
    For a single verb-noun pair record, average its 100 KWIC embeddings into one vector.

    Each record in the .pt file stores a (100, 384) tensor, i.e., one 384-dim embedding
    per KWIC sentence. We reduce this to a single (384,) mean vector representing
    how the word behaves in this particular pairing context.

    Arguments:
    - rec: dict with keys 'verb', 'noun', 'verb_embeddings', 'noun_embeddings'
    - key: 'verb_embeddings' or 'noun_embeddings' — which word's embeddings to average 
    Returns:
    - mean embedding vector of shape (384,), or None if the expected embeddings are missing/malformed

    """
    emb = rec.get(key)
    if emb is None:
        return None  # key genuinely absent from record — expected for some pairs
    if not isinstance(emb, torch.Tensor) or emb.ndim != 2:
        raise ValueError(
            f"Expected a 2-D tensor for '{key}', "
            f"got {type(emb).__name__} with shape {getattr(emb, 'shape', 'N/A')}. "
            f"Check that the .pt file was generated by the correct pipeline version."
        )
    return emb.mean(dim=0)  # collapse 100 KWICs → one mean vector, shape (384,)

def apd(emb: torch.Tensor) -> float:
    """Mean pairwise cosine distance across n context embeddings (n, d).
    APD = 0 means all contexts are identical; higher = more variable meaning."""
    normed = emb / emb.norm(dim=1, keepdim=True).clamp(min=1e-8)
    sim = normed @ normed.T                          # (n, n)
    dist = 1 - sim
    n = emb.shape[0]
    mask = torch.triu(torch.ones(n, n, dtype=torch.bool), diagonal=1)
    return dist[mask].mean().item()


def samd(a: torch.Tensor, b: torch.Tensor) -> float:
    """Symmetric Average Minimum Distance between two sets of usage embeddings.
    Greedily matches each embedding in A to its nearest in B (one-to-one),
    sampling min(|A|, |B|) from each set first.
    
    Arguments:
    - a, b: tensors of shape (n_a, d) and (n_b, d) representing n_a and n_b usage embeddings for the same verb in two conditions
      
      """
    n = min(len(a), len(b))
    a = a[:n]
    b = b[:n]
    a_n = a / a.norm(dim=1, keepdim=True).clamp(min=1e-8)
    b_n = b / b.norm(dim=1, keepdim=True).clamp(min=1e-8)
    D = (1 - a_n @ b_n.T).numpy()          # (n, n) pairwise cosine distances
    total, used_rows, used_cols = 0.0, set(), set()
    flat = D.flatten().argsort()
    for idx in flat:
        i, j = divmod(int(idx), n)
        if i in used_rows or j in used_cols:
            continue
        total += D[i, j] # a_i and b_j are each other's closest match among the remaining embeddings
        used_rows.add(i)
        used_cols.add(j)
        if len(used_rows) == n:
            break
    return total / n


def best_k(emb: torch.Tensor, k_range=range(2, 6)) -> int:
    """K-means over context embeddings; pick k by silhouette score."""
    X = emb.numpy()
    best, best_score = 2, -1.0
    for k in k_range:
        if k >= len(X):
            break
        labels = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(X)
        score = silhouette_score(X, labels)
        if score > best_score:
            best_score, best = score, k
    return best


def cos_sim(a, b):
    """
    Cosine similarity between two 1-D embedding vectors.
    Range: -1 to 1, where 1 = identical direction, 0 = orthogonal.
    In practice, contextualised embeddings are always positive so range is ~0.6–1.0.

    Arguments:
    - a, b: 1-D tensors of shape (768,)
        Returns:
    - cosine similarity as a float

    """
    return torch.nn.functional.cosine_similarity(
        a.to(DEVICE).unsqueeze(0), b.to(DEVICE).unsqueeze(0)
    ).item() 

# ---------------------------------------------------------------------------
# Load stimuli and build lookup sets for fast membership testing
# ---------------------------------------------------------------------------

stimuli       = pd.read_csv(STIMULI)
stimuli_verbs = set(stimuli['verb'].str.lower())   # which verbs we need X for
stimuli_nouns = set(stimuli['noun'].str.lower())   # which nouns we need X for
stimuli_pairs = set(stimuli['verb'].str.lower() + ' ' + stimuli['noun'].str.lower())  # which pairs we need Y for

print(f"Stimuli: {len(stimuli)} items | "
      f"{len(stimuli_verbs)} unique verbs | {len(stimuli_nouns)} unique nouns")

# ---------------------------------------------------------------------------
# PASS 1 — verbs.pt
#
# This file contains all verb-queried pairs (~7,884 pairs, verb was the Sketch Engine seed).
# Both verb and noun embeddings are stored for every pair. For each pair we:
#   1. Average the 100 KWICs → one mean embedding per word for this pairing context
#   2. Accumulate per-context verb means into verb_pool[verb]
#      → averaging verb_pool[verb] gives X[verb]: the verb prototype
#   3. Same for nouns → noun_pool_v[noun]. A noun that co-occurs with multiple seed
#      verbs accumulates one entry per seed verb. Used as fallback X[noun] if the
#      noun is not a seed word in nouns.pt.
#   4. For stimuli pairs specifically, save the mean embeddings as Y[verb] and Y[noun]
# ---------------------------------------------------------------------------

print(f"\n[1/2] Loading {VERBS_PT.name} "
      f"({VERBS_PT.stat().st_size / 1e9:.1f} GB)...", flush=True)

verbs_pt = torch.load(VERBS_PT, map_location='cpu', weights_only=False)
print(f"      {len(verbs_pt):,} pairs loaded")

verb_pool     = {}  # verb  -> [mean_emb_in_context_1, mean_emb_in_context_2, ...]
noun_pool_v   = {}  # noun  -> [mean_emb per seed-verb context] (fallback X[noun] if not in nouns.pt)
y_verb        = {}  # "verb noun" -> mean verb embedding for that stimuli pair
y_noun        = {}  # "verb noun" -> mean noun embedding for that stimuli pair
y_verb_raw    = {}  # "verb noun" -> (n_kwics, 384) raw verb embeddings for stimuli pairs
y_noun_raw    = {}  # "verb noun" -> (n_kwics, 384) raw noun embeddings for stimuli pairs

for pair_key, pair_record in verbs_pt.items(): 
    # pair key: "verb noun"
    # record keys: ['verb', 'noun', 'kwics', 'kwic_words', 'verb_embeddings', 'noun_embeddings', 'failed_indices'] 
    v = pair_record['verb']
    n = pair_record['noun']

    # Average the 100 KWICs for this pair → one context-specific mean per word
    v_mean = pair_mean_emb(pair_record, 'verb_embeddings')
    n_mean = pair_mean_emb(pair_record, 'noun_embeddings')
    if v_mean is None or n_mean is None:
        raise ValueError(
            f"Missing or malformed embeddings for pair '{pair_key}' in verbs.pt.\n"
            f"  Check that the .pt file was generated by the correct pipeline version and contains the expected keys."
        )

    # Add this context's mean to the running pool for each word.
    # Each entry in the pool represents the word as it appeared with ONE specific partner.
    verb_pool.setdefault(v, []).append(v_mean)
    noun_pool_v.setdefault(n, []).append(n_mean)

    # If this pair is one of our 190 stimuli items, save its embeddings as Y
    if pair_key in stimuli_pairs:
        y_verb[pair_key] = v_mean
        y_noun[pair_key] = n_mean
        y_verb_raw[pair_key] = pair_record['verb_embeddings'].cpu()
        y_noun_raw[pair_key] = pair_record['noun_embeddings'].cpu()

del verbs_pt  # free ~2.6 GB before loading next file

# Build X[verb]: stack all per-context means and average → one prototype vector per verb.
# Only build for stimuli verbs (no need to compute prototypes for the full vocabulary).
x_verb      = {v: torch.stack(embs).mean(0) for v, embs in verb_pool.items()
               if v in stimuli_verbs}
verb_pool_n = {v: len(embs) for v, embs in verb_pool.items()}  # pool size for diagnostics

# Build X[noun] fallback: noun prototype from verb-queried contexts only.
# Used only if the noun is not a seed word in nouns.pt (so pool will be smaller).
x_noun_fallback = {n: torch.stack(embs).mean(0) for n, embs in noun_pool_v.items()
                   if n in stimuli_nouns}

del verb_pool, noun_pool_v

if len(x_verb) == 0:
    raise RuntimeError(
        "No X[verb] prototypes built — none of the stimuli verbs appear in verbs.pt.\n"
        f"  Stimuli verbs (sample): {sorted(stimuli_verbs)[:5]}\n"
        f"  Check that pair keys in verbs.pt use lowercase lemmas separated by a space."
    )
if len(y_verb) == 0:
    raise RuntimeError(
        "No Y[verb] embeddings found — no stimuli pairs matched verbs.pt.\n"
        f"  Expected pair key format: 'verb noun' (e.g. 'kill time').\n"
        f"  Sample keys in verbs.pt: check that verbs.pt is the verb-queried file."
    )

print(f"      X[verb] ready for {len(x_verb)} stimuli verbs "
      f"(pool sizes: {min(verb_pool_n.get(v,0) for v in stimuli_verbs)}"
      f"–{max(verb_pool_n.get(v,0) for v in stimuli_verbs)} nouns)")
print(f"      Y[verb] found for {len(y_verb)}/{len(stimuli)} stimuli pairs")

# ---------------------------------------------------------------------------
# PASS 2 — nouns.pt
#
# This file contains noun-queried pairs (~15,934 pairs, noun was the Sketch Engine seed).
# We only need it to build X[noun] — the noun prototype — because the noun-queried
# data gives a much richer sampling of each noun's contexts (many different verb partners)
# than the fallback above (which only has the noun appearing with one seed verb at a time).
#
# We do NOT extract Y[noun] here because stimuli pairs were queried by verb, not noun,
# so the item-specific noun embeddings are already captured in y_noun from PASS 1.
# ---------------------------------------------------------------------------

print(f"\n[2/2] Loading {NOUNS_PT.name} "
      f"({NOUNS_PT.stat().st_size / 1e9:.1f} GB)...", flush=True)

nouns_pt = torch.load(NOUNS_PT, map_location='cpu', weights_only=False)
print(f"      {len(nouns_pt):,} pairs loaded")

noun_pool = {}  # noun -> [mean_emb_in_context_1, mean_emb_in_context_2, ...]

for pair_key, pair_record in nouns_pt.items():
    n = pair_record['noun']
    if n not in stimuli_nouns:
        continue  # skip nouns we don't need a prototype for
    n_mean = pair_mean_emb(pair_record, 'noun_embeddings')
    if n_mean is not None:
        noun_pool.setdefault(n, []).append(n_mean)

del nouns_pt  # free ~5.2 GB

# Build X[noun]: prototype from noun-queried contexts (preferred over fallback)
x_noun      = {n: torch.stack(embs).mean(0) for n, embs in noun_pool.items()}
noun_pool_n = {n: len(embs) for n, embs in noun_pool.items()}

del noun_pool

print(f"      X[noun] ready for {len(x_noun)} stimuli nouns (from nouns file)")

# For any stimuli noun not present as a seed word in nouns.pt, fall back to the
# noun prototype built from verb-queried contexts in PASS 1.
# Pool size is flagged as -1 so downstream analysis can identify these items.
for n in stimuli_nouns:
    if n not in x_noun and n in x_noun_fallback:
        x_noun[n] = x_noun_fallback[n]
        noun_pool_n[n] = -1  # flag: prototype came from verbs.pt, not nouns.pt

if len(x_noun) == 0:
    raise RuntimeError(
        "No X[noun] prototypes built — none of the stimuli nouns appear in nouns.pt or verbs.pt.\n"
        f"  Stimuli nouns (sample): {sorted(stimuli_nouns)[:5]}\n"
        f"  Check that nouns.pt is the noun-queried file and contains the expected pairs."
    )

# print(f"      X[noun] after fallback: {len(x_noun)} nouns covered")

# ---------------------------------------------------------------------------
# Compute Deltas
#
# For each stimuli item, compute:
#   verb_delta_cos = cosine_similarity(X[verb], Y[verb])
#   noun_delta_cos = cosine_similarity(X[noun], Y[noun])
#
# Both values are in ~[0.6, 1.0] for contextualised embeddings.
# Lower = more shift from prototype = more context-dependent / idiomatic behaviour.
# ---------------------------------------------------------------------------

# Build per-verb SAMD: one collocational and one productive pairing per verb.
# y_verb_raw keyed by "verb noun"; stimuli has condition per row.
pair_condition = dict(zip(
    stimuli['verb'].str.lower() + ' ' + stimuli['noun'].str.lower(),
    stimuli['Condition'].str.lower()
))

verb_samd = {}
verbs_seen = set(stimuli['verb'].str.lower())
for v in verbs_seen:
    colloc_key = next((k for k, c in pair_condition.items()
                       if k.startswith(v + ' ') and c == 'collocation'
                       and k in y_verb_raw), None)
    prod_key   = next((k for k, c in pair_condition.items()
                       if k.startswith(v + ' ') and c == 'productive'
                       and k in y_verb_raw), None)
    if colloc_key and prod_key:
        verb_samd[v] = samd(y_verb_raw[colloc_key], y_verb_raw[prod_key])

print(f"SAMD computed for {len(verb_samd)} verbs with both conditions")

print("\nComputing Deltas...", flush=True)

rows    = []
skipped = []

for _, row in stimuli.iterrows():
    v = row['verb'].lower()
    n = row['noun'].lower()
    pair_key = f"{v} {n}"

    r = {
        'item':      row['Item'],
        'verb':      v,
        'noun':      n,
        'condition': row['Condition'],
        'iRT_AJT':   row['iRT_AJT'],
    }

    # Verb Delta: how far has the verb shifted from its prototype in this pairing?
    if pair_key in y_verb and v in x_verb:
        r['verb_delta_cos']  = cos_sim(x_verb[v], y_verb[pair_key])
        r['verb_pool_size']  = verb_pool_n.get(v)
        r['verb_apd']        = apd(y_verb_raw[pair_key])
        r['verb_n_clusters'] = best_k(y_verb_raw[pair_key])
        r['verb_samd']       = verb_samd.get(v)   # same value for both pairings of this verb
    else:
        r['verb_delta_cos']  = None
        r['verb_pool_size']  = None
        r['verb_apd']        = None
        r['verb_n_clusters'] = None
        r['verb_samd']       = None
        skipped.append(f"verb missing: {pair_key}")

    # Noun Delta: how far has the noun shifted from its prototype in this pairing?
    if pair_key in y_noun and n in x_noun:
        r['noun_delta_cos']  = cos_sim(x_noun[n], y_noun[pair_key])
        r['noun_pool_size']  = noun_pool_n.get(n)
        r['noun_x_source']   = 'verbs_pt_fallback' if noun_pool_n.get(n) == -1 else 'nouns_pt'
        r['noun_apd']        = apd(y_noun_raw[pair_key])
        r['noun_n_clusters'] = best_k(y_noun_raw[pair_key])
    else:
        r['noun_delta_cos']  = None
        r['noun_pool_size']  = None
        r['noun_x_source']   = None
        r['noun_apd']        = None
        r['noun_n_clusters'] = None
        skipped.append(f"noun missing: {pair_key}")

    rows.append(r)

out_df = pd.DataFrame(rows)
out_df.to_csv(OUT, index=False)

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

print(f"\nSaved -> {OUT}  ({len(out_df)} rows)")
print(f"Skipped items: {len(skipped)}")
for s in skipped:
    print(f"  {s}")

# Pattern 4: warn if far more items were skipped than the 3 known exclusions.
# 3 missing items x (1 verb + 1 noun entry each) = up to 6 expected in skipped.
# More than 10 suggests an incomplete .pt transfer or a path mismatch.
if len(skipped) > 10:
    warnings.warn(
        f"{len(skipped)} items skipped -- more than the 6 expected from known exclusions.\n"
        f"  This likely means the .pt files are incomplete or were not fully transferred.\n"
        f"  First few skipped: {skipped[:5]}",
        RuntimeWarning,
        stacklevel=2,
    )

print("\nDelta summary by condition:")
print(out_df.groupby('condition')[['verb_delta_cos', 'noun_delta_cos']].describe().round(3))
